### PR TITLE
Fixed / changed how interacting with slash commands works 

### PR DESCRIPTION
**Pull request by Notmoodo9**

### CODE REVIEW

**Review by rigwild — COMMENTED** [review]
Hi, thanks for contributing

Can you explain what is the difference with the already existing `searchSlashCommand`? It seems to do the exact same

https://github.com/rigwild/discord-self-bot-console/blob/1468fb518e5d4180025acb523f735371015334b3/index.js#L117

**Comment by Notmoodo9** [comment]
{374F620A-86E9-4155-941F-23113460219A}
Hi, so I believe (At least in my testing, that the way you searched for commands in the past has been removed from the API. My method does the same thing(if it worked), but there is more processing client-side.

**Comment by Notmoodo9** [comment]
{3413FF8E-7688-4CD0-A005-37039EA83454}
(I made a few fixes but my system works close to the same but uses guildId, and has a pretty low rate-limit sadly)

**Comment by rigwild** [comment]
I closed this PR by doing a bad push onto your fork, my bad! the changes have been merged with some slight modifications

Thanks for contributing!

https://github.com/rigwild/discord-self-bot-console/commit/9f2eed5dda300c56321eadfa98bcac431a35b467

**Pull request closed without merging**
